In [1]:
print("hello world")

hello world


In [2]:
b = [1, 2, 3, 4]

In [3]:
b.append(5)

In [10]:
b

[1, 2, 3, 4, 5]

In [11]:
b?

In [13]:
%paste

UsageError: Line magic function `%paste` not found.


In [14]:
values = 1,2,3,4,5


In [15]:
values


(1, 2, 3, 4, 5)

In [16]:
a, b, *_ = values


In [17]:
print(a,b, _)

1 2 [3, 4, 5]


In [18]:
import numpy as np


In [19]:
data = np.random.randn(2, 3)

In [20]:
data

array([[ 1.11725329,  0.64103559, -1.17071631],
       [ 0.93680801, -1.4556256 , -1.87315205]])

In [21]:
data * 10

array([[ 11.17253293,   6.41035591, -11.70716307],
       [  9.3680801 , -14.55625601, -18.73152049]])

In [22]:
data + data

array([[ 2.23450659,  1.28207118, -2.34143261],
       [ 1.87361602, -2.9112512 , -3.7463041 ]])

In [23]:
data1 = [2,3,4,5]

In [24]:
arry1 = np.array(data1)

In [25]:
arry1

array([2, 3, 4, 5])

In [26]:
arry1.ndim

1